inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-sequel

AllCops:
  # The Ruby 2.7 changes may breaks UL server
  TargetRubyVersion: 2.6.6
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - src/constants/common_constants.rb

# It should use Rails-like style
RSpec/FilePath:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
